steps:
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g pnpm
        pnpm install --frozen-lockfile
        pnpm build
    dir: 'frontend'
    secretEnv: ['VITE_API_BASE_URL']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'storage'
      - 'rsync'
      - 'frontend/dist/'
      - 'gs://${_BUCKET_NAME}'
      - '--recursive'


options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/typescript-fullstack-onboard/secrets/VITE_API_BASE_URL/versions/latest
    env: 'VITE_API_BASE_URL'