FROM node:20-alpine AS base

WORKDIR /app

RUN npm install -g pnpm

COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY backend/package.json ./backend/

RUN pnpm install --frozen-lockfile --filter backend --prod=false

COPY backend/prisma ./backend/prisma/

ENV NODE_ENV=production

CMD ["pnpm", "--filter", "backend", "exec", "prisma", "migrate", "deploy"]
