version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: org-todo-postgres
    environment:
      POSTGRES_DB: org_todo_db
      POSTGRES_USER: org_todo_user
      POSTGRES_PASSWORD: org_todo_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - org-todo-network

volumes:
  postgres_data:

networks:
  org-todo-network:
    driver: bridge