// This file is auto-generated by @hey-api/openapi-ts

export type AnalyzeResult = {
    id: string;
    analysis: string;
};

export type _Error = {
    code: number;
    message: string;
};

export type Widget = {
    id: string;
    weight: number;
    color: 'red' | 'blue';
};

export type WidgetList = {
    items: Array<Widget>;
};

export type WidgetMergePatchUpdate = {
    id?: string;
    weight?: number;
    color?: 'red' | 'blue';
};

export type WidgetsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/widgets';
};

export type WidgetsListErrors = {
    /**
     * An unexpected error response.
     */
    default: _Error;
};

export type WidgetsListError = WidgetsListErrors[keyof WidgetsListErrors];

export type WidgetsListResponses = {
    /**
     * The request has succeeded.
     */
    200: WidgetList;
};

export type WidgetsListResponse = WidgetsListResponses[keyof WidgetsListResponses];

export type WidgetsCreateData = {
    body: Widget;
    path?: never;
    query?: never;
    url: '/widgets';
};

export type WidgetsCreateErrors = {
    /**
     * An unexpected error response.
     */
    default: _Error;
};

export type WidgetsCreateError = WidgetsCreateErrors[keyof WidgetsCreateErrors];

export type WidgetsCreateResponses = {
    /**
     * The request has succeeded.
     */
    200: Widget;
};

export type WidgetsCreateResponse = WidgetsCreateResponses[keyof WidgetsCreateResponses];

export type WidgetsDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/widgets/{id}';
};

export type WidgetsDeleteErrors = {
    /**
     * An unexpected error response.
     */
    default: _Error;
};

export type WidgetsDeleteError = WidgetsDeleteErrors[keyof WidgetsDeleteErrors];

export type WidgetsDeleteResponses = {
    /**
     * There is no content to send for this request, but the headers may be useful.
     */
    204: void;
};

export type WidgetsDeleteResponse = WidgetsDeleteResponses[keyof WidgetsDeleteResponses];

export type WidgetsReadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/widgets/{id}';
};

export type WidgetsReadErrors = {
    /**
     * An unexpected error response.
     */
    default: _Error;
};

export type WidgetsReadError = WidgetsReadErrors[keyof WidgetsReadErrors];

export type WidgetsReadResponses = {
    /**
     * The request has succeeded.
     */
    200: Widget;
};

export type WidgetsReadResponse = WidgetsReadResponses[keyof WidgetsReadResponses];

export type WidgetsUpdateData = {
    body: WidgetMergePatchUpdate;
    path: {
        id: string;
    };
    query?: never;
    url: '/widgets/{id}';
};

export type WidgetsUpdateErrors = {
    /**
     * An unexpected error response.
     */
    default: _Error;
};

export type WidgetsUpdateError = WidgetsUpdateErrors[keyof WidgetsUpdateErrors];

export type WidgetsUpdateResponses = {
    /**
     * The request has succeeded.
     */
    200: Widget;
};

export type WidgetsUpdateResponse = WidgetsUpdateResponses[keyof WidgetsUpdateResponses];

export type WidgetsAnalyzeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/widgets/{id}/analyze';
};

export type WidgetsAnalyzeErrors = {
    /**
     * An unexpected error response.
     */
    default: _Error;
};

export type WidgetsAnalyzeError = WidgetsAnalyzeErrors[keyof WidgetsAnalyzeErrors];

export type WidgetsAnalyzeResponses = {
    /**
     * The request has succeeded.
     */
    200: AnalyzeResult;
};

export type WidgetsAnalyzeResponse = WidgetsAnalyzeResponses[keyof WidgetsAnalyzeResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};